### ISSUE TITLE
seems to have an issue handling tx's...

### ISSUE THREAD

**Issue by vergecurrency** [Kefkius/encompass-mercury#5]
seems to die when an orphan comes up.. (i _think_ 416940 was an orphan)

i have the orphan handling fix for electrum in my coin daemon, so not sure on this end what the problem is.. 

INFO:electrum:blockchain: 416933 (0.035s)
INFO:electrum:blockchain: 416934 (0.020s)
INFO:electrum:blockchain: 416935 (0.021s)
INFO:electrum:blockchain: 416937 (0.037s)
INFO:electrum:blockchain: 416938 (0.022s)
INFO:electrum:blockchain: 416939 (0.025s)
INFO:electrum:blockchain: 416940 (0.025s)
INFO:electrum:blockchain reorg 416940 355af3e305f058812e1fa15b453994f326eb4197996a735c7bd5492f1da1d4f8 0000000000cbd93b45c3336b63a985a953f498640f20b4117269afaeabc71008
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/home/electrum/encompass/src/blockchain_processor.py", line 95, in do_catch_up
    self.main_iteration()
  File "/home/electrum/encompass/src/blockchain_processor.py", line 824, in main_iteration
    self.catch_up()
  File "/home/electrum/encompass/src/blockchain_processor.py", line 679, in catch_up
    block = self.getfullblock(self.storage.last_hash)
  File "/home/electrum/encompass/src/blockchain_processor.py", line 593, in getfullblock
    block = self.bitcoind('getblock', [block_hash])
  File "/home/electrum/encompass/src/blockchain_processor.py", line 139, in bitcoind
    raise BaseException(r['error'])
BaseException: {u'message': u'Block not found', u'code': -5}

**Comment by Kefkius** [comment]
This is probably related to the orphan bug, even if your coin daemon has a fix. What's needed is for encompass-mercury not to need a patched coin daemon. That's the current problem being faced.
